import { Inter } from "next/font/google";
import "../styles/main.scss";
import Providers from "@/components/context/Providers";



const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Ecommerce",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <Providers>{children}</Providers>
       
      </body>
    </html>
  );
}
